import Head from "next/head";
import { useState } from "react";

export default function Home() {
	const [inputTodo, setInputTodo] = useState("");

	const addTodo = (e) => {
		
	};

	return (
		<div className="">
			<Head>
				<title>Next TodoApp</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div>
				<form>
					<label>input todo</label>
					<input
						value={inputTodo}
						onChange={() => setInputTodo(e.target.value)}
					/>
					<button onClick={() => addTodo}>追加</button>
				</form>
			</div>
		</div>
	);
}
